// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: pkg/logistic/pb/logistic.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogisticServiceClient is the client API for LogisticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogisticServiceClient interface {
	GetCouriers(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Couriers, error)
	GetCourierByRoute(ctx context.Context, in *RouteParams, opts ...grpc.CallOption) (*Courier, error)
}

type logisticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogisticServiceClient(cc grpc.ClientConnInterface) LogisticServiceClient {
	return &logisticServiceClient{cc}
}

func (c *logisticServiceClient) GetCouriers(ctx context.Context, in *Page, opts ...grpc.CallOption) (*Couriers, error) {
	out := new(Couriers)
	err := c.cc.Invoke(ctx, "/logistic.LogisticService/GetCouriers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logisticServiceClient) GetCourierByRoute(ctx context.Context, in *RouteParams, opts ...grpc.CallOption) (*Courier, error) {
	out := new(Courier)
	err := c.cc.Invoke(ctx, "/logistic.LogisticService/GetCourierByRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogisticServiceServer is the server API for LogisticService service.
// All implementations must embed UnimplementedLogisticServiceServer
// for forward compatibility
type LogisticServiceServer interface {
	GetCouriers(context.Context, *Page) (*Couriers, error)
	GetCourierByRoute(context.Context, *RouteParams) (*Courier, error)
	mustEmbedUnimplementedLogisticServiceServer()
}

// UnimplementedLogisticServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLogisticServiceServer struct {
}

func (UnimplementedLogisticServiceServer) GetCouriers(context.Context, *Page) (*Couriers, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCouriers not implemented")
}
func (UnimplementedLogisticServiceServer) GetCourierByRoute(context.Context, *RouteParams) (*Courier, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourierByRoute not implemented")
}
func (UnimplementedLogisticServiceServer) mustEmbedUnimplementedLogisticServiceServer() {}

// UnsafeLogisticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogisticServiceServer will
// result in compilation errors.
type UnsafeLogisticServiceServer interface {
	mustEmbedUnimplementedLogisticServiceServer()
}

func RegisterLogisticServiceServer(s grpc.ServiceRegistrar, srv LogisticServiceServer) {
	s.RegisterService(&LogisticService_ServiceDesc, srv)
}

func _LogisticService_GetCouriers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Page)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticServiceServer).GetCouriers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logistic.LogisticService/GetCouriers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticServiceServer).GetCouriers(ctx, req.(*Page))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogisticService_GetCourierByRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogisticServiceServer).GetCourierByRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logistic.LogisticService/GetCourierByRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogisticServiceServer).GetCourierByRoute(ctx, req.(*RouteParams))
	}
	return interceptor(ctx, in, info, handler)
}

// LogisticService_ServiceDesc is the grpc.ServiceDesc for LogisticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogisticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logistic.LogisticService",
	HandlerType: (*LogisticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCouriers",
			Handler:    _LogisticService_GetCouriers_Handler,
		},
		{
			MethodName: "GetCourierByRoute",
			Handler:    _LogisticService_GetCourierByRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/logistic/pb/logistic.proto",
}
